name: BlueGear - Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Gradle Wrapper (if missing)
        run: |
          if [ ! -f gradlew ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper
          fi

      - name: Make gradlew executable
        run: chmod +x gradlew || echo "No gradlew yet, continuing..."

      - name: Build Debug APK
        run: ./gradlew assembleDebug || gradle assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: BlueGear-debug.apk
          path: build/outputs/apk/debug/BlueGear-debug.apk
